-- Create "accounts" table
CREATE TABLE "accounts" ("id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY, "create_time" timestamptz NOT NULL, "update_time" timestamptz NOT NULL, "name" character varying NOT NULL, "document_number" character varying NOT NULL, PRIMARY KEY ("id"));
-- Create "operation_types" table
CREATE TABLE "operation_types" ("id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY, "create_time" timestamptz NOT NULL, "update_time" timestamptz NOT NULL, "description" character varying NOT NULL, "is_debit" boolean NOT NULL, PRIMARY KEY ("id"));
-- Create "transactions" table
CREATE TABLE "transactions" ("id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY, "create_time" timestamptz NOT NULL, "update_time" timestamptz NOT NULL, "amount" double precision NOT NULL, "timestamp" timestamptz NOT NULL, "account_id" bigint NOT NULL, "operation_type_id" bigint NOT NULL, PRIMARY KEY ("id"), CONSTRAINT "transactions_accounts_transactions" FOREIGN KEY ("account_id") REFERENCES "accounts" ("id") ON UPDATE NO ACTION ON DELETE CASCADE, CONSTRAINT "transactions_operation_types_transactions" FOREIGN KEY ("operation_type_id") REFERENCES "operation_types" ("id") ON UPDATE NO ACTION ON DELETE CASCADE);
-- Create index "transaction_account_id" to table: "transactions"
CREATE INDEX "transaction_account_id" ON "transactions" ("account_id");
-- Create index "transaction_account_id_operation_type_id" to table: "transactions"
CREATE INDEX "transaction_account_id_operation_type_id" ON "transactions" ("account_id", "operation_type_id");
-- Create index "transaction_account_id_operation_type_id_timestamp" to table: "transactions"
CREATE INDEX "transaction_account_id_operation_type_id_timestamp" ON "transactions" ("account_id", "operation_type_id", "timestamp");
-- Create index "transaction_account_id_timestamp" to table: "transactions"
CREATE INDEX "transaction_account_id_timestamp" ON "transactions" ("account_id", "timestamp");
