server:
  host: ""
  port: "8080"
  debug: false
  enable_telemetry: true
  otel_endpoint: "localhost:4317"

db:
  host: "localhost"
  port: 5432
  user: "pismo"
  db_name: "pismo"
  password: ""
  # debug: true
  schema: "public"
  ssl_mode: "disable"
  migrations_folder: "./migrations"
