// Code generated by mockery v2.46.3. DO NOT EDIT.

package mocks

import (
	context "context"
	account "transactor-server/pkg/account"

	ent "transactor-server/pkg/db/ent"

	mock "github.com/stretchr/testify/mock"
)

// MockAccountDAO is an autogenerated mock type for the DAO type
type MockAccountDAO struct {
	mock.Mock
}

// Create provides a mock function with given fields: ctx, req
func (_m *MockAccountDAO) Create(ctx context.Context, req *account.CreateRequest) (*ent.Account, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *ent.Account
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *account.CreateRequest) (*ent.Account, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *account.CreateRequest) *ent.Account); ok {
		r0 = rf(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*ent.Account)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *account.CreateRequest) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Get provides a mock function with given fields: ctx, id
func (_m *MockAccountDAO) Get(ctx context.Context, id int) (*ent.Account, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *ent.Account
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int) (*ent.Account, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int) *ent.Account); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*ent.Account)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewMockAccountDAO creates a new instance of MockAccountDAO. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAccountDAO(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAccountDAO {
	mock := &MockAccountDAO{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
