// Code generated by mockery v2.46.3. DO NOT EDIT.

package mocks

import (
	ent "transactor-server/pkg/db/ent"
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockOperationTypeDAO is an autogenerated mock type for the DAO type
type MockOperationTypeDAO struct {
	mock.Mock
}

// Get provides a mock function with given fields: ctx, id
func (_m *MockOperationTypeDAO) Get(ctx context.Context, id int) (*ent.OperationType, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *ent.OperationType
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int) (*ent.OperationType, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int) *ent.OperationType); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*ent.OperationType)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewMockOperationTypeDAO creates a new instance of MockOperationTypeDAO. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockOperationTypeDAO(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockOperationTypeDAO {
	mock := &MockOperationTypeDAO{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
