// Code generated by mockery v2.46.3. DO NOT EDIT.

package mocks

import (
	transaction "transactor-server/pkg/transaction"
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockTransactionService is an autogenerated mock type for the Service type
type MockTransactionService struct {
	mock.Mock
}

// Create provides a mock function with given fields: ctx, req
func (_m *MockTransactionService) Create(ctx context.Context, req *transaction.CreateRequest) (*transaction.CreateResponse, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *transaction.CreateResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *transaction.CreateRequest) (*transaction.CreateResponse, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *transaction.CreateRequest) *transaction.CreateResponse); ok {
		r0 = rf(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*transaction.CreateResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *transaction.CreateRequest) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewMockTransactionService creates a new instance of MockTransactionService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTransactionService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTransactionService {
	mock := &MockTransactionService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
